name: Publish to Comfy registry
on:
  push:
    branches: [ main ]
    paths: [ "pyproject.toml" ]
  workflow_dispatch:

jobs:
  publish-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
